import ILLMayaSpaceSwitcherMainToolWindow

# For Development
from importlib import reload
reload(ILLMayaSpaceSwitcherMainToolWindow)

ILLMayaSpaceSwitcherMainToolWindow.ILLMayaSpaceSwitcherMainToolWindow.open_maya_main_tool_window_instance()
