import ILLMayaSpaceSwitcher.ILLMayaSpaceSwitcherConfiguration

# For Development
import DevReloader
from importlib import reload
reload(DevReloader)

# ILLMayaSpaceSwitcher.ILLMayaSpaceSwitcherConfiguration.ILLMayaSpaceSwitcherConfiguration.wipeSettings()
ILLMayaSpaceSwitcher.ILLMayaSpaceSwitcherConfiguration.ILLMayaSpaceSwitcherConfiguration.openMayaMainToolWindowInstance()
