from ILLMayaSpaceSwitcher import ILLMayaSpaceSwitcherManager

# For Development
import DevReloader
from importlib import reload
reload(DevReloader)

# ILLMayaSpaceSwitcherManager.ILLMayaSpaceSwitcherManager.wipeSettings()
ILLMayaSpaceSwitcherManager.ILLMayaSpaceSwitcherManager.openMayaMainToolWindowInstance()
