import ILLMayaSpaceSwitcherConfiguration

# For Development
import DevReloader
from importlib import reload
reload(DevReloader)

# ILLMayaSpaceSwitcherConfiguration.ILLMayaSpaceSwitcherConfiguration.wipeSettings()
ILLMayaSpaceSwitcherConfiguration.ILLMayaSpaceSwitcherConfiguration.openMayaMainToolWindowInstance()
