import ILLMayaSpaceSwitcherManager

# For Development
from importlib import reload
reload(ILLMayaSpaceSwitcherManager)

# ILLMayaSpaceSwitcherManager.ILLMayaSpaceSwitcherManager.wipeSettings()
ILLMayaSpaceSwitcherManager.ILLMayaSpaceSwitcherManager.openMayaMainToolWindowInstance()
