import ILLMayaSpaceSwitcher.ILLMayaSpaceSwitcherManager

# For Development
import DevReloader
from importlib import reload
reload(DevReloader)

# ILLMayaSpaceSwitcher.ILLMayaSpaceSwitcherManager.ILLMayaSpaceSwitcherManager.wipeSettings()
ILLMayaSpaceSwitcher.ILLMayaSpaceSwitcherManager.ILLMayaSpaceSwitcherManager.openMayaMainToolWindowInstance()
