import ILLMayaSpaceSwitcherMainToolWindow

# For Development
from importlib import reload
reload(ILLMayaSpaceSwitcherMainToolWindow)

ILLMayaSpaceSwitcherMainToolWindow.ILLMayaSpaceSwitcherMainToolWindow.openMayaMainToolWindowInstance()
